name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
        
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v3
      with:
        name: stubcc_${{ matrix.platform }}
        path: target/release/stubcc
